server:
  port: 0

app:
  client:
    url: http://SuperMart.com

spring:
  application:
    name: order-management
  datasource:
    url: jdbc:postgresql://localhost:5432/order_mgnt
    username: 'postgres'
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      user:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      user:
        max-attempts: 3
        wait-duration: 5s
